# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoppingNew' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingNew
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Alamofire', '~> 4.7'
  pod 'Kingfisher', '~> 5.0'
  pod 'iOSDropDown'
  pod 'ImageSlideshow', '~> 1.6'
  pod 'Toast-Swift', '~> 4.0.0'

end
